import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asset paths
BACKGROUND_IMAGE_PATH = "pics/background_stars.jpg"

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2.0  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
SHOT_RADIUS = 5

# Explosion effects
EXPLOSION_PARTICLE_COUNT = 12
EXPLOSION_PARTICLE_SPEED = 200
EXPLOSION_PARTICLE_LIFETIME = 0.7  # seconds
EXPLOSION_PARTICLE_SIZE = 3

# Score display
SCORE_FONT_SIZE = 32
SCORE_PADDING = 20  # Padding from screen edges
SCORE_POINTS = 100  # Points per asteroid hit

# Stun mechanics
PLAYER_STUN_DURATION = 0.7  # seconds
PLAYER_KNOCKBACK_SPEED = 400  # pixels per second
PLAYER_STUN_SPIN_SPEED = 720  # degrees per second

# Player 1 controls (WASD + SPACE)
PLAYER1_LEFT = pygame.K_a
PLAYER1_RIGHT = pygame.K_d
PLAYER1_FORWARD = pygame.K_w
PLAYER1_BACKWARD = pygame.K_s
PLAYER1_SHOOT = pygame.K_SPACE

# Player 2 controls (Arrow keys + Numpad 0)
PLAYER2_LEFT = pygame.K_LEFT
PLAYER2_RIGHT = pygame.K_RIGHT
PLAYER2_FORWARD = pygame.K_UP
PLAYER2_BACKWARD = pygame.K_DOWN
PLAYER2_SHOOT = pygame.K_KP_0
